name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Prisma 폴더가 변경되었는지 감지하는 단계 
      - name: Check prisma has changes
        uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            prisma: ["prisma/**"]

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host umc10thworkbook
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh umc10thworkbook 'sudo mkdir -p /opt/app'
          ssh umc10thworkbook 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* umc10thworkbook:/opt/app

      - name: Install dependencies
        run: |
          ssh umc10thworkbook 'cd /opt/app; npm install'
          ssh umc10thworkbook 'cd /opt/app; npx prisma generate'

      - name: Apply prisma migrations
        if: steps.paths-filter.outputs.prisma == 'true'
        run: |
          ssh umc10thworkbook 'cd /opt/app; npx prisma migrate deploy'

      - name: Copy systemd service file
        run: |
          ssh umc10thworkbook '
            echo "[Unit]
            Description=UMC 10th Project
            After=network.target

            [Service]
            User=${USER}
            ExecStart=/usr/bin/npm run start --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh umc10thworkbook 'sudo systemctl daemon-reload'
          ssh umc10thworkbook 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh umc10thworkbook 'sudo systemctl restart app'